[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["app"]
omit = ["tests/*", "autoapp.py", "scripts/*"]

[tool.flake8]
ignore = ["D401", "D202", "E226", "E302", "E41", "W503", "E203"]
max-line-length = 120
max-complexity = 30

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]